spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CnKart
    username: root
    password: password
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  

